### ISSUE TITLE
Id4的认证和授权。

### ISSUE THREAD

**Issue by WangJunZzz** [anjoy8/Blog.IdentityServer#1]
1.网上一搜id4的信息，就是认证和授权；但是很多人就是id4只做认证的功能，不做授权，每个人都各执一词，到底是怎么样的？
2.如果能做授权，比如基于角色或者策略，有什么好的可以不要硬编码在Authorize[role="admin"]这个月的吗，可以基于数据库配置？

**Comment by mingyouzhu** [comment]
> 1.网上一搜id4的信息，就是认证和授权；但是很多人就是id4只做认证的功能，不做授权，每个人都各执一词，到底是怎么样的？
> 2.如果能做授权，比如基于角色或者策略，有什么好的可以不要硬编码在Authorize[role="admin"]这个月的吗，可以基于数据库配置？

我也认同这位兄台的建议！！！！
