### ISSUE TITLE
Sorry, there was an error : invalid_scope Invalid scope

### ISSUE THREAD

**Issue by mingyouzhu** [anjoy8/Blog.IdentityServer#5]
Sorry, there was an error : invalid_scope Invalid scope

服务端配置:
![a](https://user-images.githubusercontent.com/37821420/82033293-1c92c980-96cf-11ea-82c6-fe4dddb8ee6c.png)

客户端配置:
![b](https://user-images.githubusercontent.com/37821420/82033315-24526e00-96cf-11ea-9339-e427548aa90e.png)

异常日志:
![c](https://user-images.githubusercontent.com/37821420/82033399-40eea600-96cf-11ea-89da-3d4be843c954.png)

**Comment by anjoy8** [comment]
1、这不是框架的问题，不用在这里提issue；
2、没有你的代码，我也不知道如何处理，参考我的看看；

**Comment by mingyouzhu** [comment]
解决了，原来是我的资源API配置错了
