### ISSUE TITLE
授权成功后报401错误

### ISSUE THREAD

**Issue by mingyouzhu** [anjoy8/Blog.IdentityServer#6]
大锅锅,Ids授权登录成功调用接口时HandleRequirementAsync方法没有执行怎么回事哦 总是报401未授权
![QQ图片20200521095507](https://user-images.githubusercontent.com/37821420/82514765-2beb9a00-9b49-11ea-98a9-eb463dc06860.png)

**Comment by anjoy8** [comment]
1、jwt.io解析 通过ids4返回的access_token的claims信息；
2、查看资源服务器是否配置对应的 ids4 的相关jwt认证服务；
3、查看HttpContext.User.Claims是否已经解析出来，并且是否正常；

**Comment by mingyouzhu** [comment]
> 1、jwt.io解析 通过ids4返回的access_token的claims信息；
> 2、查看资源服务器是否配置对应的 ids4 的相关jwt认证服务；
> 3、查看HttpContext.User.Claims是否已经解析出来，并且是否正常；

1. Jwt.io解析结果没看出什么问题
![token_parent](https://user-images.githubusercontent.com/37821420/82519059-580c1880-9b53-11ea-9c01-ad731a42f994.png)

2. 资源服务器配置没有什么错误的 如果有错误的肯定会影响到授权登录这块儿逻辑吧？

3. Claims已经解析出来了 但具体不确定正常 小弟道行不够深还望哥哥指点一番以下是解析结果
![parse](https://user-images.githubusercontent.com/37821420/82519253-d2d53380-9b53-11ea-949d-16f1739a5809.png)

**Comment by anjoy8** [comment]
你到底是前后端分离的简化模式，
还是mvc的授权码模式，
对比我的代码好好看看
