### ISSUE TITLE
这个项目和已部署的（https://ids.neters.club/）是一套代码吗？

### ISSUE THREAD

**Issue by Glepooek** [anjoy8/Blog.IdentityServer#7]
我用已部署的（https://ids.neters.club/）注册后跳转到页面是这样的：
![image](https://user-images.githubusercontent.com/10616673/90755703-00c24380-e30e-11ea-9741-17450705d921.png)
而我现在本项目后，运行起来，注册用户跳转后，页面是这样的：
![image](https://user-images.githubusercontent.com/10616673/90755837-336c3c00-e30e-11ea-8fc5-a00e6c8575aa.png)
是我这存在问题，还是不是一套代码？

**Comment by anjoy8** [comment]
是一套代码，你这是没有登录成功

**Comment by Glepooek** [comment]
后来又自己尝试了下，源代码中仅把监听URL修改为https就可以了，看的不是很深入，还不知道这是什么原理！！
![image](https://user-images.githubusercontent.com/10616673/91834924-44586e00-ec7b-11ea-9b75-7d403195a654.png)

**Comment by Glepooek** [comment]
后来又自己尝试了下，源代码中仅把监听URL修改为https就可以了，看的不是很深入，还不知道这是什么原理！！
![image](https://user-images.githubusercontent.com/10616673/91835143-8d102700-ec7b-11ea-915f-582b42bb8f7b.png)
