### ISSUE TITLE
[功能需求]：在线项目无法重置密码，如何在不发邮件的情况下，修改密码？

### ISSUE THREAD

**Issue by anjoy8** [anjoy8/Blog.IdentityServer#9]
正在加上。

**Comment by anjoy8** [comment]
经过思考，因不打算提供发邮件功能，所以暂停找回密码功能。
有问题联系我即可，我手动重置。

**Comment by anjoy8** [comment]
目前打算，增加密保问题，来实现【不发邮件】和【不发验证码】的情况下，非登录找回密码。

**Comment by cfzy** [comment]
82257695@qq.com
密码忘了，重置后发这邮箱吧，谢谢。

**Comment by anjoy8** [comment]
> [82257695@qq.com](mailto:82257695@qq.com)
> 密码忘了，重置后发这邮箱吧，谢谢。

未提供用户名和原邮箱，无法重置密码

**Comment by cfzy** [comment]
注册时提示82257695@qq.com被使用，不记得注册过，如果有注册过重置密码也是发这邮箱。

**Comment by lvlvlvlvlvlv** [comment]
454451808@qq.com
密码需要重置

**Comment by anjoy8** [comment]
> [454451808@qq.com](mailto:454451808@qq.com)
> 密码需要重置

已发邮件
![image](https://user-images.githubusercontent.com/28941816/126750064-b5de9379-4fd7-44e9-9288-22eb3b29c34e.png)

**Comment by zhanghuang515** [comment]
574017303@qq.com 需要密码重置

**Comment by anjoy8** [comment]
> [574017303@qq.com](mailto:574017303@qq.com) 需要密码重置

已发邮件
![image](https://user-images.githubusercontent.com/28941816/129012779-94b45e49-659e-4bd9-8978-35bb4b96bc00.png)

**Comment by zcfeng1113** [comment]
邮箱账户zlpetran@163.com 需要重置密码，之前应该有zcfeng1113和zcfeng3881,重置后保留zcfeng1113

**Comment by anjoy8** [comment]
> 邮箱账户[zlpetran@163.com](mailto:zlpetran@163.com) 需要重置密码，之前应该有zcfeng1113和zcfeng3881,重置后保留zcfeng1113

已发邮件
![Uploading image.png…]()

**Comment by zpczpc** [comment]
2524969434@qq.com

**Comment by Jays85** [comment]
519850227@qq.com 密码重置下

**Comment by mingzhichen** [comment]
539940199@qq.com
密码需要重置

**Comment by 13653415686** [comment]
344025259@qq.com  也重置一下

**Comment by tirreen** [comment]
978983958@qq.com 用户名：tirreen 请重置下密码


老张回复：
已重置，已发邮件
![image](https://user-images.githubusercontent.com/28941816/211128722-05b185d8-8729-413e-a0dc-86a6fc1fc4f8.png)

**Comment by cejpo001** [comment]
[cejpo@qq.com](mailto:cejpo@qq.com)  需要重置一下密码，谢谢


老张回复：
已重置，已发邮件
![image](https://user-images.githubusercontent.com/28941816/211128668-0a2154a4-1a34-45af-a6bc-0618bf47ab9f.png)
